version: '2'
networks:
  nats-net:
    ipam:
      config:
      - subnet: 172.25.0.0/16
services:
  nats-1:
    image: nats-streaming
    command: --config /server.cfg --cluster_id nats-1
    volumes:
    - ./seed.cfg:/server.cfg
    networks:
    - nats-net
    ports:
    - 4222:4222
    - 8222:8222
  nats-2:
    image: nats-streaming
    command: --config /server.cfg --cluster_id nats-2
    volumes:
    - ./notseed.cfg:/server.cfg
    networks:
    - nats-net
    ports:
    - 4223:4222
    - 8223:8222
  nats-3:
    image: nats-streaming
    command: --config /server.cfg --cluster_id nats-3
    volumes: 
    - ./notseed.cfg:/server.cfg 
    networks: 
    - nats-net 
    ports:
    - 4224:4222 
    - 8224:8222
